### ISSUE TITLE
ElasticSearch role is not idempotent and injects cluster.name multiple times

### ISSUE THREAD

**Issue by slawekzachcial** [devops-dojo/the-app#122]
The [role step](https://github.com/devops-dojo/the-app/blob/master/vagrant/provision/roles/elasticsearch/tasks/main.yml#L25), if run multiple times (multiple playbook executions) adds `cluster.name: ...` multiple times. This may lead to cluster name conflicts when running multiple instances in the same network.

A better approach to this would be to add `cluster.name` into the [step that is before](https://github.com/devops-dojo/the-app/blob/master/vagrant/provision/roles/elasticsearch/tasks/main.yml#L18) so it looks like:

```
- name: insert/update elasticsearch configuration block
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    block: |
      http.cors.enabled: true
      http.cors.allow-origin: http://monitoring.microservice.io
      cluster.name: {{ 100000 | random | to_uuid }}
```

and remove the step that does it today.
